/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.57
 * Generated at: 2020-08-24 11:21:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.productView;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Map.Entry;
import board.model.vo.Board;
import java.util.Map;
import product.model.vo.ProductInfo;
import java.util.List;
import java.util.List;
import productCategory.model.vo.ProductCategory;
import member.model.service.MemberService;
import member.model.vo.Member;

public final class ProductViewPhone_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/common/header.jsp", Long.valueOf(1598192553945L));
    _jspx_dependants.put("/WEB-INF/views/common/footer.jsp", Long.valueOf(1598108372851L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.model.service.MemberService");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("member.model.vo.Member");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("productCategory.model.vo.ProductCategory");
    _jspx_imports_classes.add("java.util.Map.Entry");
    _jspx_imports_classes.add("board.model.vo.Board");
    _jspx_imports_classes.add("product.model.vo.ProductInfo");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 
	Map<String, String> colorMap = (Map<String, String>)request.getAttribute("colorMap");
	List<String> capaList = (List<String>)request.getAttribute("capaList");
	ProductInfo productInfo = (ProductInfo)request.getAttribute("productInfo");
	List<Board> reviewList = (List<Board>)request.getAttribute("reviewList");
	List<ProductInfo> otherProducts = (List<ProductInfo>)request.getAttribute("otherProducts");
	String rvo = (String)request.getAttribute("rvo");
	

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	Member memberLoggedIn = (Member)session.getAttribute("memberLoggedIn");

	//쿠키확인 : 요청과 함께 전송된 쿠키확인
	boolean saveId = false;
	String memberId = "";
	Cookie[] cookies = request.getCookies();
	if(cookies != null){
		for(Cookie c : cookies){
			String key = c.getName();
			String value = c.getValue();
			System.out.println(key + " = " + value);
	
		}
	}
	

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("  <title>ELECSEMIPROJECT</title>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/css/style.css\" />\r\n");
      out.write("  <link rel=\"stylesheet\" href=\" https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100;300;400;500;700;900&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("   \t<link href=\"https://fonts.googleapis.com/css2?family=Quicksand:wght@300;400;500;600;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("  <script src=\"https://code.jquery.com/jquery-3.5.1.js\" integrity=\"sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=\"\r\n");
      out.write("  crossorigin=\"anonymous\"></script>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write(" <script type=\"text/javascript\">\r\n");
      out.write(" $(function(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#loginL\").submit(function(){\r\n");
      out.write("\t\t\tvar $memberId = $(\"#memberId\");\r\n");
      out.write("\t\t\tvar $password = $(\"#password\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(/^.{4,}$/.test($memberId.val()) == false){\r\n");
      out.write("\t\t\t\talert(\"유효한 아이디를 입력하세요.\");\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(/^.{4,}$/.test($password.val()) == false){\r\n");
      out.write("\t\t\t\talert(\"유효한 패스워드를 입력하세요.\");\t\t\t\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\treturn true;\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\t \r\n");
      out.write("\r\n");
      out.write("    //login\r\n");
      out.write("     $(document).ready(function(){\r\n");
      out.write("       $(\"#login\").click(function(){\r\n");
      out.write("         $(\".login-form\").toggleClass('active')\r\n");
      out.write("\r\n");
      out.write("       })\r\n");
      out.write("     })\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    $(document).ready(function(){\r\n");
      out.write("      $(\"#search\").click(function(){\r\n");
      out.write("        $(\".menuA\").toggleClass('hide-item')\r\n");
      out.write("        $('.search-form').toggleClass('active')\r\n");
      out.write("      })\r\n");
      out.write("    });\r\n");
      out.write("    </script>\r\n");
      out.write("  </head>\r\n");
      out.write("  \r\n");
      out.write("  <body>\r\n");
      out.write(" \r\n");
      out.write("  <!--header 시작-->\r\n");
      out.write("  <div id=\"container\">\r\n");
      out.write("  \r\n");
      out.write("  <div id=\"won\">\r\n");
      out.write("    <header id=\"header\">           \r\n");
      out.write("      \r\n");
      out.write("    \r\n");
      out.write("      <!-- nav :  메뉴, 네비게이션등을 제공하는 태그. header, aside, footer등 자유롭게 사용가능 -->\r\n");
      out.write("      <nav class=\"w_na\" style=\"margin-top: 10px;\">\r\n");
      out.write("        <ul class=\"w_u\">\r\n");
      out.write("          <li class=\"w_l\"><a href=\"");
      out.print( request.getContextPath() );
      out.write("\" ><class class=\"fa fa-bolt fa-2x\" aria-hidden=\"true\"></class></i></a></li>\r\n");
      out.write("          <li class=\"w_l\"><a href=\"");
      out.print( request.getContextPath() );
      out.write("/product/list?category=N\" class=\"menuA\">Product</a>        \r\n");
      out.write("            <ul class=\"w_u\">\r\n");
      out.write("               <li class=\"w_l\"><a href=\"");
      out.print( request.getContextPath() );
      out.write("/product/list?category=N\"class=\"menuA\" ><i class=\"fa fa-laptop\" aria-hidden=\"true\"></i>Laptop</a></li>\r\n");
      out.write("              <li class=\"w_l\"><a href=\"");
      out.print( request.getContextPath() );
      out.write("/product/list?category=P\" class=\"menuA\"><i class=\"fa fa-mobile fa-2x\" aria-hidden=\"true\"></i>Phone</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("         \r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"w_l\"><a href=\"");
      out.print( request.getContextPath() );
      out.write("/product/cList?brand=APPLE\" class=\"menuA\">Brand</a>           \r\n");
      out.write("              <ul class=\"w_u\">\r\n");
      out.write("\t           \t   <li class=\"w_l\"><a href=\"");
      out.print( request.getContextPath() );
      out.write("/product/cList?brand=APPLE\" class=\"menuA\"><i class=\"fa fa-apple\" aria-hidden=\"true\"></i>Apple </a></li> \r\n");
      out.write("\t               <li class=\"w_l\"><a href=\"");
      out.print( request.getContextPath() );
      out.write("/product/cList?brand=SAMSUNG\" class=\"menuA\"><i class=\"fa fa-scribd\" aria-hidden=\"true\"></i>Samsung </a></li> \r\n");
      out.write("\t               <li class=\"w_l\"><a href=\"");
      out.print( request.getContextPath() );
      out.write("/product/cList?brand=LG\"class=\"menuA\"><i class=\"fa fa-gg\" aria-hidden=\"true\"></i>LG </a></li>\r\n");
      out.write("              </ul>       \r\n");
      out.write("          \r\n");
      out.write("          </li>  \r\n");
      out.write("          \t");
 if(memberLoggedIn != null 
					   && MemberService.SELLER_MEMBER_ROLE.equals(memberLoggedIn.getMemberRole())){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t<li class=\"w_l\" ><a href=\"");
      out.print( request.getContextPath() );
      out.write("/seller/list?memberId=");
      out.print(memberLoggedIn.getMemberName() );
      out.write("\" class=\"menuA\">SellerList</a></li>\r\n");
      out.write("\t\t\t");
 } else { 
      out.write("\t\t\t\t\t\r\n");
      out.write("          \t\t<li class=\"w_l\"><a href=\"");
      out.print( request.getContextPath() );
      out.write("/cart/view\"class=\"menuA\">Cart</a></li>\r\n");
      out.write("            ");
 }  
      out.write("\r\n");
      out.write("          \r\n");
      out.write("          \t");
 if(memberLoggedIn != null 
					   && MemberService.ADMIN_MEMBER_ROLE.equals(memberLoggedIn.getMemberRole())){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t<li class=\"w_l\"><a href=\"");
      out.print( request.getContextPath() );
      out.write("/admin/memberList\" class=\"menuA\">AdminPage</a>\r\n");
      out.write("\t\t\t\t\t <ul class=\"w_u\">\r\n");
      out.write("              \t\t\t <li class=\"w_l\"><a href=\"");
      out.print( request.getContextPath() );
      out.write("/admin/memberList\" class=\"menuA\">MemberList </a></li> \r\n");
      out.write("              \t\t\t\t <li class=\"w_l\"><a href=\"");
      out.print( request.getContextPath() );
      out.write("/admin/stateView\" class=\"menuA\">StateView </a></li> \r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t");
 } else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("          <li class=\"w_l\"><a href=\"");
      out.print( request.getContextPath() );
      out.write("\" class=\"menuA\">MyPage</a>\r\n");
      out.write("         <ul class=\"w_u\">\r\n");
      out.write("            ");
if(memberLoggedIn != null) {
      out.write("\r\n");
      out.write("            \t<li class=\"w_l\"><a href=\"");
      out.print( request.getContextPath() );
      out.write("/orderList\" class=\"menuA\"><i class=\"fa fa-list-ul\" aria-hidden=\"true\"></i>List </a></li>\r\n");
      out.write("            ");
}else{ 
      out.write("\r\n");
      out.write("            \t<li class=\"w_l\"><a href=\"");
      out.print( request.getContextPath() );
      out.write("\" class=\"menuA\" onclick=\"alert('로그인 후에 이용하실 수 있습니다!');\"><i class=\"fa fa-list-ul\" aria-hidden=\"true\"></i>List </a></li>\r\n");
      out.write("            ");
} 
      out.write(" \r\n");
      out.write("            ");
 if(memberLoggedIn == null){ 
      out.write("\t\r\n");
      out.write("            \t<li class=\"w_l\"><a href=\"");
      out.print( request.getContextPath() );
      out.write("/member/view?memberId=\" class=\"menuA\"><i class=\"fa fa-info\" aria-hidden=\"true\"></i> Info </a></li>  \r\n");
      out.write("           ");
 } else { 
      out.write("\r\n");
      out.write("            \t<li class=\"w_l\"><a href=\"");
      out.print( request.getContextPath() );
      out.write("/member/view?memberId=");
      out.print( memberLoggedIn.getMemberId() );
      out.write("\" class=\"menuA\"><i class=\"fa fa-info\" aria-hidden=\"true\"></i> Info </a></li>  \r\n");
      out.write("          ");
 } 
      out.write("\t\r\n");
      out.write("           </ul>    \r\n");
      out.write("          </li> \r\n");
      out.write("          ");
 }  
      out.write("\r\n");
      out.write("          <!-- <li class=\"w_l\"><a href=\"#\" id=\"search\">Search</a></li> -->\r\n");
      out.write("          \r\n");
      out.write("          \t");
 if(memberLoggedIn != null) { 
      out.write(" \r\n");
      out.write("\t\t\t\t\t<span style =\"color : white;\">");
      out.print( memberLoggedIn.getMemberId() );
      out.write(" 님 \r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" value=\"로그아웃\" id =\"log-out\"onclick=\"location.href = '");
      out.print( request.getContextPath() );
      out.write("/member/logout';\"/>\r\n");
      out.write("\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t \t\t");
} else{
      out.write("\r\n");
      out.write("         \t\t <li class=\"w_l\"><a href=\"#\" id=\"login\">Login</a></li>\r\n");
      out.write("          \r\n");
      out.write("                    \r\n");
      out.write("            ");
} 
      out.write("              \r\n");
      out.write("                   \t\r\n");
      out.write("\t\t      \r\n");
      out.write("        </ul>   \r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("          <div id=\"search-product\" class=\"search-form\">\r\n");
      out.write("          <form action=\"");
      out.print( request.getContextPath() );
      out.write("/productFinder\" >\r\n");
      out.write("           <input type=\"text\" placeholder=\"Search\" name=\"searchKeyword\">\r\n");
      out.write("             \r\n");
      out.write("                  <button id=\"w_sfB\"><i class=\"fa fa-search\" aria-hidden=\"true\"  onclick=\"");
      out.print( request.getContextPath() );
      out.write("/ProductCategory\"></i></button>\r\n");
      out.write("\t\t\t</form> \r\n");
      out.write("          </div>\r\n");
      out.write("          \r\n");
      out.write("\r\n");
      out.write("        <div class=\"login-form\">\r\n");
 if(memberLoggedIn == null){ 
      out.write("\r\n");
      out.write("          <form id=\"loginL\" \r\n");
      out.write("          action=\"");
      out.print( request.getContextPath() );
      out.write("/member/login\" \r\n");
      out.write("          method=\"POST\"\t\r\n");
      out.write("          class=\"input-group\">\r\n");
      out.write("            <br>\r\n");
      out.write("            <input type=\"text\" name=\"memberId\" class=\"input-field\" placeholder=\"User ID\" required >\r\n");
      out.write("           \r\n");
      out.write("            <input type=\"password\" name=\"password\" class=\"input-field\" placeholder=\"Enter Password\" required>\r\n");
      out.write("            <!-- <input type=\"checkbox\" class=\"check-box\"><span> Remember Password </span> -->\r\n");
      out.write("            <br>\r\n");
      out.write("            <br>\r\n");
      out.write("          \r\n");
      out.write("            <button type=\"submit\" class=\"submit-btn\">LogIn</button>\r\n");
      out.write("              \r\n");
      out.write("        </form>          \r\n");
      out.write("\t      <button type=\"submit\" class=\"submit-btn\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/member/enroll';\">Register</button>\r\n");
      out.write("             \r\n");
      out.write("        </div>\r\n");
      out.write("      </nav>\r\n");
      out.write("      ");
 } 
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("     \r\n");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("    </header>\r\n");
      out.write("    \r\n");
      out.write("    <div style=\"height:70px; background-color:#000000d9; width: 1280px; \"></div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <section id=\"content_WH\" >\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/productView.css\" />\r\n");
      out.write("            <div id=\"first-boxJ\">\r\n");
      out.write("                <div id=\"left-lineJ\">\r\n");
      out.write("                    <div id=\"imgSectionJ\">\r\n");
      out.write("                        <img src=\"");
      out.print( request.getContextPath() );
      out.print( productInfo.getProductImg() );
      out.write("/thum.png\" alt=\"\" id=\"detailJ\">\r\n");
      out.write("                       <h2 id=\"productNameJ\">");
      out.print( productInfo.getProductName() );
      out.write("</h2>\r\n");
      out.write("                        <h1 id=\"productGradeJ\">★ ");
      out.print( productInfo.getProductGrade() );
      out.write("</h1>\r\n");
      out.write("                        <p id=\"productDescJ\">\r\n");
      out.write("                           ");
 String[] desc = productInfo.getProductDesc().split(",");
      out.write("\r\n");
      out.write("                          ");
 for(int d=0; d<desc.length; d++){ 
      out.write("\r\n");
      out.write("                        \t\t");
      out.print( desc[d]);
      out.write(" <br>\r\n");
      out.write("                           ");
 } 
      out.write("\r\n");
      out.write("                        </p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"right-lineJ\">\r\n");
      out.write("                   <div id=\"colorOptionJ\">\r\n");
      out.write("                        <p class=\"optionTitleJ\" >Choose Your Color</p>\r\n");
      out.write("                        <div id=\"colorOptionBoxJ\"  >\r\n");
      out.write("                           ");
 for (Entry<String, String> entry : colorMap.entrySet()) { 
      out.write(" \r\n");
      out.write("                            <div class=\"color-nameJ\" >\r\n");
      out.write("                                <div class=\"circleJ\" style=\"background-color : ");
      out.print( entry.getValue() );
      out.write("\"></div> \r\n");
      out.write("                                <p class=\"colorPJ\">");
      out.print( entry.getKey() );
      out.write("</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            ");
} 
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div id=\"hrJ\"></div>\r\n");
      out.write("                    <div id=\"capacityOptionJ\">\r\n");
      out.write("                        <p class=\"optionTitleJ\" >Choose Your Capacity</p>\r\n");
      out.write("                        <div id=\"capaOptionBoxJ\" >\r\n");
      out.write("                        \t");
 for(String capa : capaList) {
      out.write("\r\n");
      out.write("                            <div class=\"capa-nameJ\" >\r\n");
      out.write("                               <span>");
      out.print( capa );
      out.write("</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            ");
 } 
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div id=\"hrJ\"></div>\r\n");
      out.write("                      <div id=\"totalRowJ\">\r\n");
      out.write("                     \t");
 int price = productInfo.getPrice() * (100 - productInfo.getDiscountRate()) / 100; 
      out.write("\r\n");
      out.write("                        <p id=\"totalPriceJ\" class=\"korBoldJ\" value=\"");
      out.print( price );
      out.write("\">Price : ₩ ");
      out.print( price );
      out.write("</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div id=\"button-rowJ\">\r\n");
      out.write("                        <button id=\"btnCartJ\" onclick=\"addToCart(");
      out.print( productInfo.getInch());
      out.write(");\">Cart</button>\r\n");
      out.write("                        <input type=\"hidden\" id=\"inputProdCodeJ\" value=\"");
      out.print( productInfo.getProductCode() );
      out.write("\" name=\"prodCode\" />\r\n");
      out.write("                        <button id=\"btnBuyJ\" onclick=\"buyProduct(");
      out.print( productInfo.getInch());
      out.write(");\">Buy Now</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("               <div id=\"second-boxJ\">\r\n");
      out.write("                <div class=\"slideJ\">\r\n");
      out.write("\t\t\t        <img id=\"backJ\" src=\"");
      out.print( request.getContextPath() );
      out.write("/images/JH/back.png\" alt=\"\" width=\"50\">\r\n");
      out.write("\t\t\t       \t<ul>\r\n");
      out.write("\t\t\t            <li><img class=\"adImgJ\" src=\"");
      out.print( request.getContextPath() );
      out.print( productInfo.getProductImg() );
      out.write("/adImg1.png\" alt=\"\" width=\"1280\" height=\"300\"></li>\r\n");
      out.write("\t\t\t            <li><img class=\"adImgJ\" src=\"");
      out.print( request.getContextPath() );
      out.print( productInfo.getProductImg() );
      out.write("/adImg2.png\" alt=\"\" width=\"1280\" height=\"300\"></li>\r\n");
      out.write("\t\t\t        </ul>\r\n");
      out.write("\t\t\t        <img id=\"nextJ\" src=\"");
      out.print( request.getContextPath() );
      out.write("/images/JH/next.png\" alt=\"\" width=\"50\">\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div id=\"third-boxJ\">\r\n");
      out.write("                <div class=\"hrJ\"></div>\r\n");
      out.write("                <div id=\"review-rowJ\" class=\"menuJ\">\r\n");
      out.write("                   <p class=\"slideTitleJ\">Review</p>\r\n");
      out.write("                   <div class=\"rotateJ\" id=\"review-rotateJ\">+</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"reviewJ\" class=\"slide-contentJ\"> \r\n");
      out.write("                 ");
 if(rvo.equals("on")){
      out.write("\r\n");
      out.write("                    <div id=\"inputReviewJ\">\r\n");
      out.write("                       <form action=\"");
      out.print( request.getContextPath() );
      out.write("/board/insert\" method=\"post\" id=\"formReviewJ\">\r\n");
      out.write("                       <div id=\"box1J\"><span class=\"korBoldJ\">리뷰작성하기</span></div>\r\n");
      out.write("                       <div id=\"box2J\"><input type=\"text\" value=\"\" id=\"textReviewJ\" class=\"korJ\" name=\"inputReview\"></div>\r\n");
      out.write("                       <div class=\"box3J\">\r\n");
      out.write("                            <p class=\"star_ratingJ\">\r\n");
      out.write("                                <a href=\"\" class=\"onJ\">★</a>\r\n");
      out.write("                                <a href=\"\" class=\"onJ\">★</a>\r\n");
      out.write("                                <a href=\"\" class=\"onJ\">★</a>\r\n");
      out.write("                                <a href=\"\">★</a>\r\n");
      out.write("                                <a href=\"\">★</a>\r\n");
      out.write("                            </p>\r\n");
      out.write("                            <input type=\"hidden\" name=\"reivewGrade\" id=\"reivewGradeJ\" value=\"\"/>\r\n");
      out.write("                            <input type=\"hidden\" name=\"prodCode\" value=\"");
      out.print( productInfo.getProductCode());
      out.write("\"/>\r\n");
      out.write("                            <input type=\"hidden\" name=\"prodInch\" value=\"");
      out.print( productInfo.getInch());
      out.write("\"/>\r\n");
      out.write("                        </div>\r\n");
      out.write("                       <div id=\"box4J\"><button id=\"btnReviewJ\" type=\"submit\">OK</button></div>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                 ");
 } 
      out.write("\r\n");
      out.write("                    <table id=\"review-tableJ\">\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <th class=\"korBoldJ\">아이디</th>\r\n");
      out.write("                            <th class=\"korBoldJ\">한줄평</th>\r\n");
      out.write("                            <th class=\"korBoldJ\">평점</th>\r\n");
      out.write("                            <th class=\"korBoldJ\">날짜</th>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                       ");
if(reviewList == null || reviewList.isEmpty()){ 
      out.write("\r\n");
      out.write("\t                       <tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th colspan=\"4\">작성된 리뷰가 없습니다.</th>\r\n");
      out.write("\t\t\t\t\t\t   </tr>\r\n");
      out.write("                       ");
}else { 
                       	  for(Board b : reviewList){
      out.write("\r\n");
      out.write("\t                       \t<tr>\r\n");
      out.write("\t                            <th>");
      out.print( b.getBoardWriter() );
      out.write("</th>\r\n");
      out.write("\t                            <th class=\"korJ\">");
      out.print( b.getBoardContent() );
      out.write("</th>\r\n");
      out.write("\t                            <th>");
      out.print( b.getBoardGrade() );
      out.write("</th>\r\n");
      out.write("\t                            <th>");
      out.print( b.getBoardDate() );
      out.write("</th>\r\n");
      out.write("\t                        </tr>\r\n");
      out.write("\t                      ");
 }
                        } 
      out.write("\r\n");
      out.write("                    </table>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"hrJ\"></div>\r\n");
      out.write("                <div id=\"product-rowJ\" class=\"menuJ\">\r\n");
      out.write("                    <p class=\"slideTitleJ\">Other Product</p>\r\n");
      out.write("                    <div class=\"rotateJ\" id=\"product-rotateJ\">+</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"productJ\" class=\"slide-contentJ\">\r\n");
      out.write("                    <p id=\"compStmJ\">Compare with other items</p>\r\n");
      out.write("                     ");
 for(int i=0; i<otherProducts.size(); i++){
      out.write("\r\n");
      out.write("        \t\t\t");
 ProductInfo pi = otherProducts.get(i); 
      out.write("\r\n");
      out.write("                    <div  class=\"prodBoxJ\">\r\n");
      out.write("                        <img src=\"");
      out.print( request.getContextPath());
      out.print( pi.getProductImg() );
      out.write("/thum.png\" alt=\"\" class=\"prodBoxImgJ\">\r\n");
      out.write("                        <h2 class=\"prodBoxNameJ\">");
      out.print( pi.getProductName() );
      out.write("</h2>\r\n");
      out.write("                        <p class=\"prodBoxDescJ\" >\r\n");
      out.write("                        \t");
 String[] temp = pi.getProductDesc().split(","); 
      out.write("\r\n");
      out.write("                        \t");
 for(int t=0; t<temp.length; t++){ 
      out.write("\r\n");
      out.write("                        \t\t");
      out.print( temp[t]);
      out.write(" <br>\r\n");
      out.write("                            ");
 } 
      out.write("\r\n");
      out.write("                        </p>\r\n");
      out.write("                        <button class=\"prodBoxBtnJ\" onclick=\"moveToProduct();\">Buy</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                 ");
 } 
      out.write("\r\n");
      out.write("                  </div>\r\n");
      out.write("                <div class=\"hrJ\"></div>\r\n");
      out.write("                <br><br>\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("    \r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    var deg = -45;\r\n");
      out.write("    var totalDeg = 0;\r\n");
      out.write("    $(\"div.menuJ\").click(function(){\r\n");
      out.write("        $(this).next().slideToggle(\"easeOut\")\r\n");
      out.write("                      .siblings(\"p\").slideUp(\"easeOut\");\r\n");
      out.write("\r\n");
      out.write("        deg *= -1;\r\n");
      out.write("        totalDeg += deg; \r\n");
      out.write("        $(this).children(\"div\").css('transform','rotate(' + totalDeg + 'deg)');\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    $( \".star_ratingJ a\" ).click(function() {\r\n");
      out.write("        $(this).parent().children(\"a\").removeClass(\"onJ\");\r\n");
      out.write("        $(this).addClass(\"onJ\").prevAll(\"a\").addClass(\"onJ\");\r\n");
      out.write("        return false;\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("    $(\"div.color-nameJ\").click(function(){\r\n");
      out.write("        var products = document.querySelectorAll(\".color-nameJ\");\r\n");
      out.write("        console.log(products);\r\n");
      out.write("        for(var i=0; i<products.length; i++){\r\n");
      out.write("            products[i].style.border = \"2px solid darkgray\"; \r\n");
      out.write("            products[i].setAttribute(\"value\",\"off\");\r\n");
      out.write("        }\r\n");
      out.write("        $(this).css({\"border-color\": \"#0070c9\", \r\n");
      out.write("                    \"border-width\":\"2px\", \r\n");
      out.write("                    \"border-style\":\"solid\"})\r\n");
      out.write("               .attr('value','on');\r\n");
      out.write("       \r\n");
      out.write("       \r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("    $(\"div.capa-nameJ\").click(function(){\r\n");
      out.write("        var products = document.querySelectorAll(\".capa-nameJ\");\r\n");
      out.write("        console.log(products);\r\n");
      out.write("        for(var i=0; i<products.length; i++){\r\n");
      out.write("            products[i].style.border = \"2px solid darkgray\"; \r\n");
      out.write("            products[i].setAttribute(\"value\",\"off\");\r\n");
      out.write("        }\r\n");
      out.write("        $(this).css({\"border-color\": \"#0070c9\", \r\n");
      out.write("                    \"border-width\":\"2px\", \r\n");
      out.write("                    \"border-style\":\"solid\"})\r\n");
      out.write("               .attr('value','on');\r\n");
      out.write("       \r\n");
      out.write("\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    function buyProduct(inch){\r\n");
      out.write("    \t\r\n");
      out.write("    \t if(examineSelectOption() < 2){\r\n");
      out.write("    \t\talert(\"옵션을 선택해주세요!\");\r\n");
      out.write("    \t}else{\r\n");
      out.write("    \t\tvar confirmBuy = confirm(\"상품을 구매하시겠습니까?\"); \r\n");
      out.write("        \tif(confirmBuy == true){\r\n");
      out.write("        \t\tvar orderSerialcode = findSerialCode(inch);\r\n");
      out.write("        \t\tvar orderQuantityList = 1;\r\n");
      out.write("        \t\tvar totalPrice = $(\"#totalPriceJ\").attr('value');\r\n");
      out.write("        \t\t\r\n");
      out.write("        \t\tlocation.href=\"");
      out.print(request.getContextPath());
      out.write("/order/orderpage?orderSerialcode=\"+orderSerialcode+\"&orderQuantityList=\"+orderQuantityList+\"&totalPrice=\"+totalPrice;\r\n");
      out.write("        \t}\r\n");
      out.write("    \t}\r\n");
      out.write("    \tvar orderSerialcode = findSerialCode(inch);\r\n");
      out.write("\t\tvar orderQuantityList = 1;\r\n");
      out.write("\t\tvar totalPrice = $(\"#totalPriceJ\").attr('value');\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\tfunction addToCart(inch){\r\n");
      out.write("    \t\r\n");
      out.write("\t\tif(examineSelectOption() < 2){\r\n");
      out.write("    \t\talert(\"옵션을 선택해주세요!\");\r\n");
      out.write("    \t}else{\r\n");
      out.write("    \t\tvar addCart = confirm(\"장바구니에 상품을 담으시겠습니까?\"); \r\n");
      out.write("        \tif(addCart == true){\r\n");
      out.write("        \t\t\r\n");
      out.write("        \t\tvar serialCode = findSerialCode(inch);\r\n");
      out.write("        \t\tlocation.href=\"");
      out.print(request.getContextPath());
      out.write("/cart/insert?serialCode=\"+serialCode;\t\r\n");
      out.write("        \t}\r\n");
      out.write("    \t}\t\t\r\n");
      out.write("    }\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#formReviewJ\").submit(function(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar stars = document.getElementsByClassName(\"onJ\");\r\n");
      out.write("\t\tvar grade = stars.length;\r\n");
      out.write("\t\tconsole.log(grade);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar stars = document.getElementsByClassName(\"onJ\");\r\n");
      out.write("\t\tvar grade = stars.length;\r\n");
      out.write("\t\tconsole.log(grade);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#reivewGradeJ\").val(grade);\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tfunction findSerialCode(inch){\r\n");
      out.write("\t\tvar prodCode = $(\"#button-rowJ input[type='hidden']\").val();\r\n");
      out.write("      \tvar colorOption = document.querySelectorAll(\"div.color-nameJ\");\r\n");
      out.write("    \tvar capaOption = document.querySelectorAll(\"div.capa-nameJ\");\r\n");
      out.write("    \tvar color;\r\n");
      out.write("    \tvar capa;\r\n");
      out.write("  \r\n");
      out.write("    \tfor(var i=0; i<colorOption.length; i++){\r\n");
      out.write("    \t\tif(colorOption[i].getAttribute(\"value\") == 'on'){\r\n");
      out.write("    \t\t\tcolor = findColorCode(colorOption[i].innerText);\r\n");
      out.write("    \t\t}\r\n");
      out.write("        } \r\n");
      out.write("    \t\r\n");
      out.write("    \tfor(var j=0; j<capaOption.length; j++){\r\n");
      out.write("    \t\tif(capaOption[j].getAttribute(\"value\") == 'on'){\r\n");
      out.write("    \t\t\tcapa = findCapaCode(capaOption[j].innerText);\r\n");
      out.write("    \t\t}\r\n");
      out.write("    \t}\r\n");
      out.write("    \t \r\n");
      out.write("    \tvar serialCode = prodCode + color + \"I\" + inch + capa;\r\n");
      out.write("    \treturn serialCode;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tfunction findCapaCode(capacity){\r\n");
      out.write("\t\tvar capaCode;\r\n");
      out.write("\t\tswitch(capacity){\r\n");
      out.write("\t\tcase \"32GB\" : \r\n");
      out.write("\t\t\tcapaCode = \"M32\";\r\n");
      out.write("\t\t\tbreak;\r\n");
      out.write("\t\tcase \"64GB\" : \r\n");
      out.write("\t\t\tcapaCode = \"M64\";\r\n");
      out.write("\t\t\tbreak;\r\n");
      out.write("\t\tcase \"256GB\" : \r\n");
      out.write("\t\t\tcapaCode = \"M256\";\r\n");
      out.write("\t\t\tbreak;\r\n");
      out.write("\t\tcase \"512GB\" : \r\n");
      out.write("\t\t\tcapaCode = \"M512\";\r\n");
      out.write("\t\t\tbreak;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\treturn capaCode;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tfunction findColorCode(colorName){\r\n");
      out.write("\t\tvar colorCode;\r\n");
      out.write("\t\tswitch(colorName){\r\n");
      out.write("\t\tcase \"Black\" : \r\n");
      out.write("\t\t\tcolorCode = \"C1\";\r\n");
      out.write("\t\t\tbreak;\r\n");
      out.write("\t\tcase \"Red\" : \r\n");
      out.write("\t\t\tcolorCode = \"C2\";\r\n");
      out.write("\t\t\tbreak;\r\n");
      out.write("\t\tcase \"Blue\" : \r\n");
      out.write("\t\t\tcolorCode = \"C3\";\r\n");
      out.write("\t\t\tbreak;\r\n");
      out.write("\t\tcase \"Green\" : \r\n");
      out.write("\t\t\tcolorCode = \"C5\";\r\n");
      out.write("\t\t\tbreak;\r\n");
      out.write("\t\tcase \"Gray\" : \r\n");
      out.write("\t\t\tcolorCode = \"C6\";\r\n");
      out.write("\t\t\tbreak;\r\n");
      out.write("\t\tcase \"White\" : \r\n");
      out.write("\t\t\tcolorCode = \"C7\";\r\n");
      out.write("\t\t\tbreak;\r\n");
      out.write("\t\tcase \"Purple\" : \r\n");
      out.write("\t\t\tcolorCode = \"C9\";\r\n");
      out.write("\t\t\tbreak;\r\n");
      out.write("\t\tcase \"Silver\" : \r\n");
      out.write("\t\t\tcolorCode = \"C10\";\r\n");
      out.write("\t\t\tbreak;\r\n");
      out.write("\t\tcase \"Gold\" : \r\n");
      out.write("\t\t\tcolorCode = \"C11\";\r\n");
      out.write("\t\t\tbreak;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\treturn colorCode;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction examineSelectOption(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar colorOption = document.querySelectorAll(\"div.color-nameJ\");\r\n");
      out.write("    \tvar capaOption = document.querySelectorAll(\"div.capa-nameJ\");\r\n");
      out.write("    \t\r\n");
      out.write("    \tvar count = 0;\r\n");
      out.write("    \tfor(var i=0; i<colorOption.length; i++){\r\n");
      out.write("    \t\tif(colorOption[i].getAttribute(\"value\") == 'on'){\r\n");
      out.write("    \t\t\tcount += 1;\r\n");
      out.write("    \t\t\t\r\n");
      out.write("    \t\t}\r\n");
      out.write("        } \r\n");
      out.write("    \t\r\n");
      out.write("    \tfor(var j=0; j<capaOption.length; j++){\r\n");
      out.write("    \t\tif(capaOption[j].getAttribute(\"value\") == 'on'){\r\n");
      out.write("    \t\t\tcount += 1;\r\n");
      out.write("    \t\t}\r\n");
      out.write("    \t}\r\n");
      out.write("\t\t\r\n");
      out.write("    \treturn count;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t $(document).ready(function(){\r\n");
      out.write("\t      var imgs;\r\n");
      out.write("\t      var img_count;\r\n");
      out.write("\t      var img_position = 1;\r\n");
      out.write("\r\n");
      out.write("\t      imgs = $(\".slideJ ul\");\r\n");
      out.write("\t      img_count = imgs.children().length;\r\n");
      out.write("\r\n");
      out.write("\t      //버튼을 클릭했을 때 함수 실행\r\n");
      out.write("\t      $('#backJ').click(function () {\r\n");
      out.write("\t        back();\r\n");
      out.write("\t      });\r\n");
      out.write("\t      $('#nextJ').click(function () {\r\n");
      out.write("\t        next();\r\n");
      out.write("\t      });\r\n");
      out.write("\r\n");
      out.write("\t      function back() {\r\n");
      out.write("\t        if(1 < img_position){\r\n");
      out.write("\t          imgs.animate({\r\n");
      out.write("\t            left:'+=1280px'\r\n");
      out.write("\t          });\r\n");
      out.write("\t          img_position--;\r\n");
      out.write("\t        }\r\n");
      out.write("\t      }\r\n");
      out.write("\t      function next() {\r\n");
      out.write("\t        if(img_count>img_position){\r\n");
      out.write("\t          imgs.animate({\r\n");
      out.write("\t            left:'-=1280px'\r\n");
      out.write("\t          });\r\n");
      out.write("\t          img_position++;\r\n");
      out.write("\t        }\r\n");
      out.write("\t      }\r\n");
      out.write("\r\n");
      out.write("\t    });\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</section>\r\n");
      out.write("<div>\r\n");
      out.write("\t\t<footer id=\"footer\">\r\n");
      out.write("\t\t\t<p style=\"color:white;\">&lt;Copyright 1998-2020 <strong>KH정보교육원</strong>. All rights reserved.&gt;</p>\r\n");
      out.write("\t\t</footer>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("    ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
