/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.57
 * Generated at: 2020-08-24 11:04:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.order;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import cart.model.vo.Cart;
import java.util.List;
import member.model.vo.Member;
import java.util.List;
import productCategory.model.vo.ProductCategory;
import member.model.service.MemberService;
import member.model.vo.Member;

public final class orderpage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/common/header.jsp", Long.valueOf(1598192553945L));
    _jspx_dependants.put("/WEB-INF/views/common/footer.jsp", Long.valueOf(1598108372851L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.model.service.MemberService");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("member.model.vo.Member");
    _jspx_imports_classes.add("productCategory.model.vo.ProductCategory");
    _jspx_imports_classes.add("cart.model.vo.Cart");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	Member memberLoggedIn = (Member)session.getAttribute("memberLoggedIn");

	//쿠키확인 : 요청과 함께 전송된 쿠키확인
	boolean saveId = false;
	String memberId = "";
	Cookie[] cookies = request.getCookies();
	if(cookies != null){
		for(Cookie c : cookies){
			String key = c.getName();
			String value = c.getValue();
			System.out.println(key + " = " + value);
	
		}
	}
	

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("  <title>ELECSEMIPROJECT</title>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/css/style.css\" />\r\n");
      out.write("  <link rel=\"stylesheet\" href=\" https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100;300;400;500;700;900&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("   \t<link href=\"https://fonts.googleapis.com/css2?family=Quicksand:wght@300;400;500;600;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("  <script src=\"https://code.jquery.com/jquery-3.5.1.js\" integrity=\"sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=\"\r\n");
      out.write("  crossorigin=\"anonymous\"></script>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write(" <script type=\"text/javascript\">\r\n");
      out.write(" $(function(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#loginL\").submit(function(){\r\n");
      out.write("\t\t\tvar $memberId = $(\"#memberId\");\r\n");
      out.write("\t\t\tvar $password = $(\"#password\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(/^.{4,}$/.test($memberId.val()) == false){\r\n");
      out.write("\t\t\t\talert(\"유효한 아이디를 입력하세요.\");\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(/^.{4,}$/.test($password.val()) == false){\r\n");
      out.write("\t\t\t\talert(\"유효한 패스워드를 입력하세요.\");\t\t\t\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\treturn true;\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\t \r\n");
      out.write("\r\n");
      out.write("    //login\r\n");
      out.write("     $(document).ready(function(){\r\n");
      out.write("       $(\"#login\").click(function(){\r\n");
      out.write("         $(\".login-form\").toggleClass('active')\r\n");
      out.write("\r\n");
      out.write("       })\r\n");
      out.write("     })\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    $(document).ready(function(){\r\n");
      out.write("      $(\"#search\").click(function(){\r\n");
      out.write("        $(\".menuA\").toggleClass('hide-item')\r\n");
      out.write("        $('.search-form').toggleClass('active')\r\n");
      out.write("      })\r\n");
      out.write("    });\r\n");
      out.write("    </script>\r\n");
      out.write("  </head>\r\n");
      out.write("  \r\n");
      out.write("  <body>\r\n");
      out.write(" \r\n");
      out.write("  <!--header 시작-->\r\n");
      out.write("  <div id=\"container\">\r\n");
      out.write("  \r\n");
      out.write("  <div id=\"won\">\r\n");
      out.write("    <header id=\"header\">           \r\n");
      out.write("      \r\n");
      out.write("    \r\n");
      out.write("      <!-- nav :  메뉴, 네비게이션등을 제공하는 태그. header, aside, footer등 자유롭게 사용가능 -->\r\n");
      out.write("      <nav class=\"w_na\" style=\"margin-top: 10px;\">\r\n");
      out.write("        <ul class=\"w_u\">\r\n");
      out.write("          <li class=\"w_l\"><a href=\"");
      out.print( request.getContextPath() );
      out.write("\" ><class class=\"fa fa-bolt fa-2x\" aria-hidden=\"true\"></class></i></a></li>\r\n");
      out.write("          <li class=\"w_l\"><a href=\"");
      out.print( request.getContextPath() );
      out.write("/product/list?category=N\" class=\"menuA\">Product</a>        \r\n");
      out.write("            <ul class=\"w_u\">\r\n");
      out.write("               <li class=\"w_l\"><a href=\"");
      out.print( request.getContextPath() );
      out.write("/product/list?category=N\"class=\"menuA\" ><i class=\"fa fa-laptop\" aria-hidden=\"true\"></i>Laptop</a></li>\r\n");
      out.write("              <li class=\"w_l\"><a href=\"");
      out.print( request.getContextPath() );
      out.write("/product/list?category=P\" class=\"menuA\"><i class=\"fa fa-mobile fa-2x\" aria-hidden=\"true\"></i>Phone</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("         \r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"w_l\"><a href=\"");
      out.print( request.getContextPath() );
      out.write("/product/cList?brand=APPLE\" class=\"menuA\">Brand</a>           \r\n");
      out.write("              <ul class=\"w_u\">\r\n");
      out.write("\t           \t   <li class=\"w_l\"><a href=\"");
      out.print( request.getContextPath() );
      out.write("/product/cList?brand=APPLE\" class=\"menuA\"><i class=\"fa fa-apple\" aria-hidden=\"true\"></i>Apple </a></li> \r\n");
      out.write("\t               <li class=\"w_l\"><a href=\"");
      out.print( request.getContextPath() );
      out.write("/product/cList?brand=SAMSUNG\" class=\"menuA\"><i class=\"fa fa-scribd\" aria-hidden=\"true\"></i>Samsung </a></li> \r\n");
      out.write("\t               <li class=\"w_l\"><a href=\"");
      out.print( request.getContextPath() );
      out.write("/product/cList?brand=LG\"class=\"menuA\"><i class=\"fa fa-gg\" aria-hidden=\"true\"></i>LG </a></li>\r\n");
      out.write("              </ul>       \r\n");
      out.write("          \r\n");
      out.write("          </li>  \r\n");
      out.write("          \t");
 if(memberLoggedIn != null 
					   && MemberService.SELLER_MEMBER_ROLE.equals(memberLoggedIn.getMemberRole())){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t<li class=\"w_l\" ><a href=\"");
      out.print( request.getContextPath() );
      out.write("/seller/list?memberId=");
      out.print(memberLoggedIn.getMemberName() );
      out.write("\" class=\"menuA\">SellerList</a></li>\r\n");
      out.write("\t\t\t");
 } else { 
      out.write("\t\t\t\t\t\r\n");
      out.write("          \t\t<li class=\"w_l\"><a href=\"");
      out.print( request.getContextPath() );
      out.write("/cart/view\"class=\"menuA\">Cart</a></li>\r\n");
      out.write("            ");
 }  
      out.write("\r\n");
      out.write("          \r\n");
      out.write("          \t");
 if(memberLoggedIn != null 
					   && MemberService.ADMIN_MEMBER_ROLE.equals(memberLoggedIn.getMemberRole())){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t<li class=\"w_l\"><a href=\"");
      out.print( request.getContextPath() );
      out.write("/admin/memberList\" class=\"menuA\">AdminPage</a>\r\n");
      out.write("\t\t\t\t\t <ul class=\"w_u\">\r\n");
      out.write("              \t\t\t <li class=\"w_l\"><a href=\"");
      out.print( request.getContextPath() );
      out.write("/admin/memberList\" class=\"menuA\">MemberList </a></li> \r\n");
      out.write("              \t\t\t\t <li class=\"w_l\"><a href=\"");
      out.print( request.getContextPath() );
      out.write("/admin/stateView\" class=\"menuA\">StateView </a></li> \r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t");
 } else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("          <li class=\"w_l\"><a href=\"");
      out.print( request.getContextPath() );
      out.write("\" class=\"menuA\">MyPage</a>\r\n");
      out.write("         <ul class=\"w_u\">\r\n");
      out.write("            ");
if(memberLoggedIn != null) {
      out.write("\r\n");
      out.write("            \t<li class=\"w_l\"><a href=\"");
      out.print( request.getContextPath() );
      out.write("/orderList\" class=\"menuA\"><i class=\"fa fa-list-ul\" aria-hidden=\"true\"></i>List </a></li>\r\n");
      out.write("            ");
}else{ 
      out.write("\r\n");
      out.write("            \t<li class=\"w_l\"><a href=\"");
      out.print( request.getContextPath() );
      out.write("\" class=\"menuA\" onclick=\"alert('로그인 후에 이용하실 수 있습니다!');\"><i class=\"fa fa-list-ul\" aria-hidden=\"true\"></i>List </a></li>\r\n");
      out.write("            ");
} 
      out.write(" \r\n");
      out.write("            ");
 if(memberLoggedIn == null){ 
      out.write("\t\r\n");
      out.write("            \t<li class=\"w_l\"><a href=\"");
      out.print( request.getContextPath() );
      out.write("/member/view?memberId=\" class=\"menuA\"><i class=\"fa fa-info\" aria-hidden=\"true\"></i> Info </a></li>  \r\n");
      out.write("           ");
 } else { 
      out.write("\r\n");
      out.write("            \t<li class=\"w_l\"><a href=\"");
      out.print( request.getContextPath() );
      out.write("/member/view?memberId=");
      out.print( memberLoggedIn.getMemberId() );
      out.write("\" class=\"menuA\"><i class=\"fa fa-info\" aria-hidden=\"true\"></i> Info </a></li>  \r\n");
      out.write("          ");
 } 
      out.write("\t\r\n");
      out.write("           </ul>    \r\n");
      out.write("          </li> \r\n");
      out.write("          ");
 }  
      out.write("\r\n");
      out.write("          <!-- <li class=\"w_l\"><a href=\"#\" id=\"search\">Search</a></li> -->\r\n");
      out.write("          \r\n");
      out.write("          \t");
 if(memberLoggedIn != null) { 
      out.write(" \r\n");
      out.write("\t\t\t\t\t<span style =\"color : white;\">");
      out.print( memberLoggedIn.getMemberId() );
      out.write(" 님 \r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" value=\"로그아웃\" id =\"log-out\"onclick=\"location.href = '");
      out.print( request.getContextPath() );
      out.write("/member/logout';\"/>\r\n");
      out.write("\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t \t\t");
} else{
      out.write("\r\n");
      out.write("         \t\t <li class=\"w_l\"><a href=\"#\" id=\"login\">Login</a></li>\r\n");
      out.write("          \r\n");
      out.write("                    \r\n");
      out.write("            ");
} 
      out.write("              \r\n");
      out.write("                   \t\r\n");
      out.write("\t\t      \r\n");
      out.write("        </ul>   \r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("          <div id=\"search-product\" class=\"search-form\">\r\n");
      out.write("          <form action=\"");
      out.print( request.getContextPath() );
      out.write("/productFinder\" >\r\n");
      out.write("           <input type=\"text\" placeholder=\"Search\" name=\"searchKeyword\">\r\n");
      out.write("             \r\n");
      out.write("                  <button id=\"w_sfB\"><i class=\"fa fa-search\" aria-hidden=\"true\"  onclick=\"");
      out.print( request.getContextPath() );
      out.write("/ProductCategory\"></i></button>\r\n");
      out.write("\t\t\t</form> \r\n");
      out.write("          </div>\r\n");
      out.write("          \r\n");
      out.write("\r\n");
      out.write("        <div class=\"login-form\">\r\n");
 if(memberLoggedIn == null){ 
      out.write("\r\n");
      out.write("          <form id=\"loginL\" \r\n");
      out.write("          action=\"");
      out.print( request.getContextPath() );
      out.write("/member/login\" \r\n");
      out.write("          method=\"POST\"\t\r\n");
      out.write("          class=\"input-group\">\r\n");
      out.write("            <br>\r\n");
      out.write("            <input type=\"text\" name=\"memberId\" class=\"input-field\" placeholder=\"User ID\" required >\r\n");
      out.write("           \r\n");
      out.write("            <input type=\"password\" name=\"password\" class=\"input-field\" placeholder=\"Enter Password\" required>\r\n");
      out.write("            <!-- <input type=\"checkbox\" class=\"check-box\"><span> Remember Password </span> -->\r\n");
      out.write("            <br>\r\n");
      out.write("            <br>\r\n");
      out.write("          \r\n");
      out.write("            <button type=\"submit\" class=\"submit-btn\">LogIn</button>\r\n");
      out.write("              \r\n");
      out.write("        </form>          \r\n");
      out.write("\t      <button type=\"submit\" class=\"submit-btn\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/member/enroll';\">Register</button>\r\n");
      out.write("             \r\n");
      out.write("        </div>\r\n");
      out.write("      </nav>\r\n");
      out.write("      ");
 } 
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("     \r\n");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("    </header>\r\n");
      out.write("    \r\n");
      out.write("    <div style=\"height:70px; background-color:#000000d9; width: 1280px; \"></div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <section id=\"content_WH\" >\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/css/order.css\" />\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery-3.5.1.js\"></script>\r\n");
	
	
	String totalPrice = (String)request.getAttribute("totalPrice");
	String orderSerialcode = (String)request.getAttribute("orderSerialcode");
	String orderQuantityList = (String)request.getAttribute("orderQuantityList");
 

      out.write(" \r\n");
      out.write("<script>\r\n");
      out.write("function kakao(){\r\n");
      out.write("\r\n");
      out.write("\tvar url = \"");
      out.print( request.getContextPath() );
      out.write("/pay/kakao\";\r\n");
      out.write("\tvar title = \"kakaoPay\";\r\n");
      out.write("\tvar spec = \"left=400px, top=60px, width=400px, height=520px\";\r\n");
      out.write("\t\r\n");
      out.write("\topen(url, title, spec);\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("function goPopup(){\r\n");
      out.write("\t// 주소검색을 수행할 팝업 페이지를 호출합니다.\r\n");
      out.write("\t// 호출된 페이지(jusopopup.jsp)에서 실제 주소검색URL(http://www.juso.go.kr/addrlink/addrLinkUrl.do)를 호출하게 됩니다.\r\n");
      out.write("\tvar pop = window.open(\"/elec/popup/jusoPopup.jsp\",\"pop\",\"width=570,height=420, scrollbars=yes, resizable=yes\"); \r\n");
      out.write("\t\r\n");
      out.write("\t// 모바일 웹인 경우, 호출된 페이지(jusopopup.jsp)에서 실제 주소검색URL(http://www.juso.go.kr/addrlink/addrMobileLinkUrl.do)를 호출하게 됩니다.\r\n");
      out.write(" //var pop = window.open(\"/popup/jusoPopup.jsp\",\"pop\",\"scrollbars=yes, resizable=yes\"); \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function jusoCallBack(roadFullAddr){\r\n");
      out.write("\t\t\r\n");
      out.write("\tvar tfAddress = document.querySelector(\"#paddress\");\r\n");
      out.write("\ttfAddress.value = roadFullAddr;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\t $(\"#selfadd\").click(function () {\r\n");
      out.write("\t\t if($(\"input[name=selfadd]:checked\") ){\r\n");
      out.write("\t\t\t document.getElementById(\"userName\").value = \"");
      out.print(memberLoggedIn.getMemberName());
      out.write("\"\r\n");
      out.write("\t\t\t document.getElementById(\"userPhone\").value = \"");
      out.print(memberLoggedIn.getMemberPhone());
      out.write("\"\r\n");
      out.write("\t\t\t document.getElementById(\"paddress\").value = \"");
      out.print(memberLoggedIn.getMemberAddress());
      out.write("\"\t\r\n");
      out.write("\t\t }\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<form action=\"");
      out.print( request.getContextPath() );
      out.write("/pay/kakao\" name=\"orderpage\" method=\"post\">\r\n");
      out.write("    <div class=\"Payment_formH\">\r\n");
      out.write("    <div class=\"paywonH\">\r\n");
      out.write("    <strong id=\"payH\">결제:</strong><strong id=\"wonH\">₩ ");
      out.print( totalPrice);
      out.write("</strong>\r\n");
      out.write("    <br> <hr>\r\n");
      out.write("\r\n");
      out.write("<br>\r\n");
      out.write("<h1 id=\"text1H\">주문하신 제품(들)이 어디로 배송되길 원하십니까?</h1> \r\n");
      out.write("\r\n");
      out.write("<div class=\"Input_formH\">\r\n");
      out.write("<!-- <span id=\"text2\">이름및 주소입력</span> &nbsp; -->\r\n");
      out.write("<input type=\"radio\" name=\"selfadd\" id=\"selfadd\"  value=\"selfadd\">기본배송지 <br><br>\r\n");
      out.write("<input type=\"text\" name=\"userName\" class=\"userH\" id=\"userName\" value=\"");
      out.write("\" placeholder=\"이름\">\r\n");
      out.write("<input type=\"text\" name=\"userPhone\" class=\"userH\" id=\"userPhone\" value=\"");
      out.write("\"  placeholder=\"연락처\">\r\n");
      out.write("<input type=\"text\" class=\"user1H\" name=\"paddress\" id=\"paddress\"  value=\"");
      out.write("\" placeholder=\"상세주소\">\r\n");
      out.write("<input type=\"button\" id=\"add_btn\" onclick=\"goPopup();\" value=\"주소찾기\">\r\n");
      out.write("<input type=\"text\" name=\"request\" class=\"userH\" id=\"request\" placeholder=\"배송요청사항(선택사항)\">\r\n");
      out.write("<h2 class=\"paymentH\">결제수단</h2>\r\n");
      out.write("<hr>\r\n");
      out.write("<select name=\"\" class=\"userH\"style=\"width: 520px;\">\r\n");
      out.write("    <option value=\"\" class=\"userH\" style=\"font-family: 'Quicksand', sans-serif;\">카카오페이결제</option>\r\n");
      out.write("</select> <br>\r\n");
      out.write("<input type=\"submit\" id=\"paybtn\" value=\"결제 페이지로 이동()\"><br><br><br><br><br><br>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<input type=\"hidden\" id=\"memberId\" name=\"memberId\" value=\"");
      out.print(memberId );
      out.write("\" />\r\n");
      out.write("<input type=\"hidden\" id=\"orderSerialcode\" name=\"orderSerialcode\" value=\"");
      out.print(orderSerialcode );
      out.write("\" />\r\n");
      out.write("<input type=\"hidden\" id=\"totalPrice\" name=\"totalPrice\" value=\"");
      out.print(totalPrice );
      out.write("\" />\r\n");
      out.write("<input type=\"hidden\" id=\"orderQuantityList\" name=\"orderQuantityList\" value=\"");
      out.print(orderQuantityList );
      out.write("\" />\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</section>\r\n");
      out.write("<div>\r\n");
      out.write("\t\t<footer id=\"footer\">\r\n");
      out.write("\t\t\t<p style=\"color:white;\">&lt;Copyright 1998-2020 <strong>KH정보교육원</strong>. All rights reserved.&gt;</p>\r\n");
      out.write("\t\t</footer>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
